### PR TITLE
feat: add support for dot notations in DataObject Relations

### PR DESCRIPTION
**Pull request by saas-archipro**

### CODE REVIEW

**Comment by mleutenegger** [comment]
Hi there, thanks for the PR, will have a look at it. The Testing fails seem to stem from a limitation in the docker image, will check too.

**Comment by mleutenegger** [comment]
(Please ignore the failing test, it seems to stem from a cached action)

So far so good, I assume you want to add the dot notation for relations (as described [here](https://docs.silverstripe.org/en/4/developer_guides/model/relations/#polymorphic-has-one)). would you be able to provide a testcase for this? I know that currently, there is none, but this would help get the coverage up 🙃.

**Comment by sciutand** [comment]
@mleutenegger I've added the test.. couldn't get the static db relations to be picked up automatically.. so had to add to the Config directly. Not sure if there is a better way?

**Comment by mleutenegger** [comment]
Looks good to me. It's interesting that the statically defined relations aren't picked up, have you tried to use it in a project that uses named relations?

**Review by mleutenegger — APPROVED** [review]
:+1:

**Pull request merged**
